Topl/flutter_annulus

lib/main.dart
lib/models/block_details.dart
lib/models/block_slider.dart
lib/presentation/header.dart
lib/presentation/layout.dart
lib/widgets/block_slider.dart
lib/widgets/block_view.dart
pubspec.lock
pubspec.yaml

Adds Block view carousel with dummy data

feat(ANNULUS-96): adds block view

---

lib/blocks/models/block.dart
lib/blocks/providers/block_provider.dart

I'd like to ask for some input
- suggestion for fixing the error in the second fetching method

Annulus-114

---

lib/chain/models/chain.dart
lib/chain/providers/chain_provider.dart
lib/chain/sections/chain_info.dart

Product: Summary of key stats

---

lib/blocks/sections/block_slider.dart
lib/blocks/widgets/block_slider/block_view.dart
lib/chain/widgets/chain_info/lower_stat_with_icon.dart
lib/chain/widgets/chain_info/lower_stats_without_icon.dart
lib/home/screen/home_screen.dart

Product: View latest blocks

---

.github/workflows/push.yml
Dockerfile

The Docker build is broken because it's using the wrong Flutter version.
Update the Docker base image to use Flutter 3.10.
https://github.com/Topl/flutter_annulus/actions/runs/5016703594/jobs/8993941432
*

Fix docker build

---

lib/blocks/sections/block_details_drawer.dart
lib/blocks/sections/block_tabbar_view.dart
lib/blocks/widgets/block_slider/block_view.dart
lib/transactions/sections/transaction_row_item.dart
lib/transactions/sections/transaction_table.dart
lib/transactions/sections/transaction_table_header.dart
lib/transactions/sections/transactions.dart

feat(ANNULUT-136): Product: Improvement to Block Details page

---

lib/transactions/providers/transactions_provider.dart

- fetching transaction by id
- mix of mock data with real data (update to only using real data coming)

Transactions ANNULUS-174

---

envoy.yaml
lib/blocks/providers/block_provider.dart
lib/chain/models/chains.dart
lib/transactions/providers/transactions_provider.dart
pubspec.yaml

- added envoy config to run proxy for grpc web
- updated port for local network so that you can connect via proxy
- updated name in transaction mock data to fix error (will be updated soon)
- updated number of blocks fetched to fix errors
- [ manual testing]

grpc-web support

---

README.md
envoy.yaml
lib/blocks/providers/block_provider.dart
lib/chain/models/chains.dart
lib/transactions/providers/transactions_provider.dart
pubspec.yaml

ANNULUS-186 GRPC-Web 

---

lib/chain/sections/chain_info.dart
lib/home/screen/home_screen.dart
lib/shared/constants/strings.dart
lib/shared/widgets/header.dart
lib/shared/widgets/layout.dart

ANNULUS-175: Product: Tooltips for Home page

---

lib/blocks/providers/block_provider.dart

Bug Fix for block slider infinite load

Fix for block slider infinite load

---

lib/transactions/sections/transaction_details_drawer.dart

Remove invalid fields from transactions details page

Product: Remove invalid fields from Transaction Details page

---

lib/blocks/providers/block_provider.dart
lib/blocks/sections/block_slider.dart
lib/blocks/widgets/block_slider/block_view.dart
lib/chain/providers/selected_chain_provider.dart
lib/shared/constants/ui.dart

This fixes the bug of the block slider animation looking a bit odd
[ANNULUS-230](https://topl.atlassian.net/browse/ANNULUS-230?atlOrigin=eyJpIjoiYzI2M2IwZWJmYzZkNDk2MmIzYjFmYmUxYjZhNTIzOWMiLCJwIjoiaiJ9)
[ANNULUS-230]: https://topl.atlassian.net/browse/ANNULUS-230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Block Slider Bug Fix

---

lib/blocks/providers/block_provider.dart
lib/shared/utils/extensions.dart
lib/transactions/models/transaction.dart
lib/transactions/providers/transactions_provider.dart
lib/transactions/sections/transaction_details_drawer.dart
lib/transactions/utils/utils.dart
pubspec.yaml

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Update Model Values ANNULUS-260 ANNULUS-261

---

lib/transactions/models/transaction.dart
lib/transactions/providers/transactions_provider.dart
lib/transactions/utils/utils.dart

Get tx by index in state
Fixes # ANNULUS-259

Get tx by index ANNULUS-259

---

lib/blocks/providers/block_provider.dart
lib/blocks/sections/block_slider.dart
lib/blocks/widgets/block_slider/block_view.dart
lib/chain/providers/chart_providers/average_transaction_fee_provider.dart
lib/chain/providers/selected_chain_provider.dart
lib/chain/sections/line_graph.dart
lib/shared/providers/config_provider.dart

Fixes the average transaction fee for line graph

Fix Average Transaction fee for line graph

---

lib/search/models/search_result.dart
lib/search/providers/search_provider.dart
lib/search/sections/custom_search_bar.dart
lib/search/sections/search_results.dart
lib/shared/providers/mock_state_provider.dart
lib/shared/utils/decode_id.dart
lib/shared/utils/nav_utils.dart
lib/transactions/providers/utxo_provider.dart

Implements Search via state and rpc
ANNULUS-288

Search Implementation

---

lib/blocks/providers/block_provider.dart
lib/transactions/providers/transactions_provider.dart
lib/transactions/utils/utils.dart

- refactor getting the next block that contains transactions
- when fetching the next transaction for adding to state, search for the next block that has transaction instead of assuming that the next block down the chain has transactions.

ANNULUS-289 Refactor Getting Next Block

---

lib/blocks/models/block.dart
lib/blocks/providers/block_provider.dart
lib/transactions/providers/transactions_provider.dart
lib/transactions/utils/utils.dart

- fixes depth at block0
- when searching for a populated block to fetch transactions, add that block to the state if it is not in state.
- util methods for convenience

ANNULUS-304 State by Depth (Fixed at Block0)

---

lib/chain/providers/selected_chain_provider.dart
lib/chain/sections/add_new_network.dart
lib/chain/sections/chainname_dropdown.dart
lib/chain/utils/chain_utils.dart
lib/transactions/widgets/custom_transaction_widgets.dart

ANNULUS-294 Remove Custom Network

---

Dockerfile

After applying Gatekeeper rules to our k8s cluster, I need to make some changes to the Dockerfile to pass the checks. 
We need a non-root user for the Docker image. Add the `USER` command and change the folder ownership.

[BN-1146]: Add non-root user for Dockerfile

---

lib/blocks/providers/block_provider.dart
lib/shared/services/hive/hives.dart

ANNULUS-325: Cache Blocks By Height

---

lib/chain/sections/chain_info.dart
lib/chain/sections/chart_section.dart
lib/chain/widgets/chain_info/custom_tooltip.dart
lib/shared/widgets/header.dart
lib/transactions/widgets/drawer.dart

Replace all StatefulWidgets with HookWidgets in AnnulusFixes # (issue)
Manually

Replace all StatefulWidgets with HookWidgets in Annulus

---

Makefile
lib/chain/models/chains.dart

Updated the url for the dev endpoint
DAPP-404

bug(DAPP-404): Updated the url endpoint for dev network

---

lib/blocks/providers/block_provider.dart
lib/chain/providers/chart_provider.dart
lib/chain/utils/chain_utils.dart
lib/transactions/providers/transactions_provider.dart
lib/transactions/utils/utils.dart
pubspec.yaml

Adds timeout to get first populated block
DAPP-410

bug(DAPP-410): Add timeout to get first populated block

---

lib/shared/constants/strings.dart

Updates Epoch Tooltip
DAPP-448

Update to tooltips

---

lib/shared/providers/url_launcher_provider.dart
lib/shared/widgets/header.dart
pubspec.yaml
test/header/desktop_header_test.dart
test/header/required_header_tests.dart
test/shared/mocks/url_launcher_mocks.dart

- Adds a faucet link in the desktop view
- required test obj
- desktop tests
Please note:
1. no mobile designs were provided. This is only on desktop
2. I adjusted the placement of the light/dark theme toggle to confirm to the Figma designs. It is now to the right of the chainname dropdown menu
3. I believe the spacing on the designs 

DAPP-455 Faucet Link

---

Makefile
lib/home/screen/home_screen.dart
lib/shared/constants/strings.dart
lib/transactions/models/transaction.dart
lib/transactions/providers/transactions_provider.dart
lib/transactions/sections/details/desktop_transaction_details_page.dart
lib/transactions/sections/details/detail_item.dart
lib/transactions/sections/details/detail_section.dart
lib/transactions/sections/details/lower_detail_section.dart
lib/transactions/sections/details/mobile_transaction_details_page.dart
lib/transactions/sections/details/transaction_details_page.dart
lib/transactions/sections/details/upper_detail_section.dart
lib/transactions/sections/transactions.dart
lib/transactions/utils/extension.dart
lib/transactions/utils/utils.dart
test/shared/mocks/genus_mocks.dart
test/shared/utils/block_utils.dart
test/shared/utils/chain_info_utils.dart
test/shared/utils/transaction_utils.dart
test/transactions/desktop_transaction_details_test.dart
test/transactions/mobile_transaction_details_test.dart
test/transactions/tablet_transaction_details_test.dart
test/transactions/utils/transaction_utils.dart

Adds metadata to transactions
DAPP-469

feat(DAPP-469): Meta data in transactions

---

Dockerfile

Currently, running Annulus locally via Docker has some issues:
```
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: can not modify /etc/nginx/conf.d/default.conf (read-only file system?)
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/12/14 17:38:21 [warn] 1#1: the "user" directive makes sense only if the master process runs with super-user privileges, ignored in …
```

Fix Issues Running Annulus Docker Image Locally
